export const portfolios = [                    
    {title:"TRACK FIT",
    image: "https://general-farnaztowhidi.s3.ca-central-1.amazonaws.com/Snapshot_trackFit.jpg",
    description: "Full crud application",
    sourceCode: "https://github.com/aerlikh17/track-fit-app",
    deploy: "https://track-fit-app.herokuapp.com/",
    technology: "html, CSS, Python, Django, PostreSQL," },

    {title:"FOOD SERVICE",
    image: "https://general-farnaztowhidi.s3.ca-central-1.amazonaws.com/Snapshot_MacDonald.jpg",
    description: "Dry rest api",
    sourceCode: "https://github.com/FarnazTowhidi/macDonald",
    deploy: "https://macdonald-generalassembly.herokuapp.com/",
    technology: "Express, MongoDB, Python" },

    {title:"CHATTERBOX",
    image: "https://general-farnaztowhidi.s3.ca-central-1.amazonaws.com/Snapshot_Chatterbox.jpg",
    description: "MERN-stack architecture, single page application",
    sourceCode: "https://github.com/tungolra/Chatterbox-mern-app",
    deploy: "https://chatterbox-sei-55.herokuapp.com/",
    technology: "React, Express, AWS S3, Socket.io, MVC" },
    
    {title:"WARCARD ",
    image: "https://general-farnaztowhidi.s3.ca-central-1.amazonaws.com/Snapshot_warcardGame.jpg",
    description: "Includes shuffling and win/loss logic",
    sourceCode: "https://github.com/FarnazTowhidi/warCardGame",
    deploy: "https://farnaztowhidi.github.io/warCardGame/",
    technology: "Html, CSS, JavaScript" },
    
    {title:"ACADEMIC",
    image: "https://general-farnaztowhidi.s3.ca-central-1.amazonaws.com/Snapshot_arash.jpg",
    description: "Platform for courses, supervising, ... ",
    sourceCode: "",
    deploy: "",
    url: "http://ahlashkari.com/",
    technology: "Html, CSS, Asp" },

    {title:"BIOSSENTIALS",
    image: "https://general-farnaztowhidi.s3.ca-central-1.amazonaws.com/Snapshot_biossentials.jpg",
    description: " lj l jl j lk j",
    sourceCode: "",
    deploy: "",
    url: "https://www.biossentials.com/",
    technology: "Html, CSS, Asp, SEO" },

    {title:"IMMIGRATION",
    image: "https://general-farnaztowhidi.s3.ca-central-1.amazonaws.com/Snapshot_swallow.jpg",
    description: " lj l jl j lk j",
    sourceCode: "",
    deploy: "http://ahlashkari.com/",
    technology: "Html, CSS" },
   ]