export const portfolios = [                    
    {title:"Track Fit",
    image: "https://general-farnaztowhidi.s3.ca-central-1.amazonaws.com/Snapshot_trackFit.jpg",
    description: "Full crud application",
    sourceCode: "https://github.com/aerlikh17/track-fit-app",
    deploy: "http://http://ahlashkari.com/",
    technology: "html, CSS, Python, Django, PostreSQL, Heroku" },

    {title:"Food Service",
    image: "https://general-farnaztowhidi.s3.ca-central-1.amazonaws.com/Snapshot_MacDonald.jpg",
    description: "DRY REST API for fully-functional styled McDonald's inventory application",
    sourceCode: "https://github.com/FarnazTowhidi/macDonald",
    deploy: "http://http://ahlashkari.com/",
    technology: "Express.MongoDB, Python" },

    {title:"ChatterBox",
    image: "https://general-farnaztowhidi.s3.ca-central-1.amazonaws.com/Snapshot_Chatterbox.jpg",
    description: "MERN-stack architecture, single page application",
    sourceCode: "https://github.com/tungolra/Chatterbox-mern-app",
    deploy: "https://chatterbox-sei-55.herokuapp.com/",
    technology: "HTML, CSS, React, MVC architecture, Express, AWS S3, Socket.io" },
    
    {title:"WarCard ",
    image: "https://general-farnaztowhidi.s3.ca-central-1.amazonaws.com/Snapshot_warcardGame.jpg",
    description: "Includes shuffling and win/loss logic",
    sourceCode: "https://github.com/FarnazTowhidi/warCardGame",
    deploy: "https://chatterbox-sei-55.herokuapp.com/",
    technology: "Html, CSS, JavaScript, Deploy on github" },
    
    {title:"Academic ...",
    image: "https://general-farnaztowhidi.s3.ca-central-1.amazonaws.com/Snapshot_arash.jpg",
    description: "Platform for teaching courses, supervising, publication, ... ",
    sourceCode: "",
    deploy: "",
    url: "http://ahlashkari.com/",
    technology: "Html, CSS, Asp" },

    {title:"Biossentials",
    image: "https://general-farnaztowhidi.s3.ca-central-1.amazonaws.com/Snapshot_biossentials.jpg",
    description: " lj l jl j lk j",
    sourceCode: "NA",
    deploy: "",
    url: "https://www.biossentials.com/",
    technology: "Html, CSS, SEO, Asp" },

    {title:"Swallow",
    image: "https://general-farnaztowhidi.s3.ca-central-1.amazonaws.com/Snapshot_swallow.jpg",
    description: " lj l jl j lk j",
    sourceCode: "",
    deploy: "http://ahlashkari.com/",
    technology: "Html, CSS" },
   ]