export const portfolios = [                    
    {title:"TRACK FIT",
    image: "https://general-farnaztowhidi.s3.ca-central-1.amazonaws.com/Snapshot_trackFit.jpg",
    description: "Full crud application, for recording the user's daily fitness log",
    sourceCode: "https://github.com/aerlikh17/track-fit-app",
    deploy: "https://track-fit-app.herokuapp.com/",
    technology: "HTML, CSS, Python, Django, PostreSQL," },

    {title:"FOOD SERVICE",
    image: "https://general-farnaztowhidi.s3.ca-central-1.amazonaws.com/Snapshot_MacDonald.jpg",
    description: "DRY REST API for fully-functional styled McDonald's inventory application",
    sourceCode: "https://github.com/FarnazTowhidi/macDonald",
    deploy: "https://macdonald-generalassembly.herokuapp.com/",
    technology: "Express/Node, MongoDB, Python" },

    {title:"CHATTERBOX",
    image: "https://general-farnaztowhidi.s3.ca-central-1.amazonaws.com/Snapshot_Chatterbox.jpg",
    description: "Mern stack application, Responsive single page application, Uploader AWS S3",
    sourceCode: "https://github.com/tungolra/Chatterbox-mern-app",
    deploy: "https://chatterbox-sei-55.herokuapp.com/",
    technology: "React, Express, MongoDB, Socket.io, MVC" },
    
    {title:"WARCARD ",
    image: "https://general-farnaztowhidi.s3.ca-central-1.amazonaws.com/Snapshot_warcardGame.jpg",
    description: "The browser base game, using application state, manipulating DOM",
    sourceCode: "https://github.com/FarnazTowhidi/warCardGame",
    deploy: "https://farnaztowhidi.github.io/warCardGame/",
    technology: "HTML, CSS, JavaScript" },
    
    {title:"ACADEMIC",
    image: "https://general-farnaztowhidi.s3.ca-central-1.amazonaws.com/Snapshot_arash.jpg",
    description: "Create the responsive website for supervising, teaching, publication, workshop and datasets",
    sourceCode: "",
    deploy: "",
    url: "http://ahlashkari.com/",
    technology: "HTML, CSS, Asp" },

    {title:"BIOSSENTIALS",
    image: "https://general-farnaztowhidi.s3.ca-central-1.amazonaws.com/Snapshot_biossentials.jpg",
    description: "Redesign website for aromatherapy and organic botanical products ",
    sourceCode: "",
    deploy: "",
    url: "https://www.biossentials.com/",
    technology: "HTML, CSS, Asp, SEO" },

    {title:"IMMIGRATION",
    image: "https://general-farnaztowhidi.s3.ca-central-1.amazonaws.com/Snapshot_swallow.jpg",
    description: "Design a website for immigation consultant that facilate applicant process  ",
    sourceCode: "/swallow",
    deploy: "http://ahlashkari.com/",
    technology: "HTML, CSS" },
   ]